---
title: "Bayesian estimation supersedes the t test"
output: html_document
---

```{r}
library(BEST)
```

```{r}
# load test data
control <- c(1.6, 3.3, 2.5, 0.7, 2.9, 4.9, 3.3, 1.7, 2.1, 2.5, 2.1, 1.6, 2.6, 7.2, 6.6)
experiment <- c(3.1, 2.1, 4.5, 4.8, 5.4, 9.2, 5.6, 7.1, 4.7, 4.3, 4.7, 5.7, 6.7, 10.1,5.4)
```

```{r}
#get means
mean(control)
mean(experiment)
```

```{r}
# run BEST
# Note: I put the experiment data as first input, as it has the highest mean, otherwise I negative values in output, which does not make snese for this context. 

best_out <- BESTmcmc(experiment, control, parallel=TRUE)

```

```{r}
# MCMC fit results for BEST analysis
best_out
```

```{r}
# summary of BEST anaylsis
summary(best_out)
```

```{r}
# Difference of means plot 
# Note: If the 95% Highest Density Interval (HDI), for the difference of means, does NOT include zero, then there is a credible difference. However, effect size is arguably a better measure of difference.

plot(best_out)

```

```{r}
# All BEST plots, which includes effect size.
# Note: If the 95% Highest Density Interval (HDI), for the effect size, does NOT include zero, then there is a credible difference. 

plotAll(best_out)

```

```{r}
# optional: check for normality
qqnorm(control)
qqline(control)

qqnorm(experiment)
qqline(experiment)
```
