---
title: "ggcor_&_pca_test"
output: html_document
---

```{r}
library(ggcorrplot)
```

```{r}
cor_matrix_p <- round(cor(mtcars, method="pearson"), 2)
```

```{r}
ggcorrplot(cor_matrix_p, hc.order = TRUE, type = "lower",
   lab = TRUE)
```

```{r}
cor_matrix_s <- round(cor(mtcars, method="spearman"), 2)
```

```{r}
ggcorrplot(cor_matrix_s, hc.order = TRUE, type = "lower",
   lab = TRUE)
```

```{r}
cor_matrix_k <- round(cor(mtcars, method="kendall"), 2)
```

```{r}
ggcorrplot(cor_matrix_k, hc.order = TRUE, type = "lower",
   lab = TRUE)
```

```{r}
library(FactoMineR)
library(factoextra)
```

```{r}
# run PCA
pca_mtcars <- PCA(mtcars)
```

```{r}
# make scree plot
fviz_screeplot(pca_mtcars)
```

```{r}
# find all PC's with an eigen value > 1
pca_mtcars$eig
pca_mtcars$eig > 1
```

```{r}
# get percent PC contribution for each variable for PC 1 
fviz_contrib(pca_mtcars, choice="var", axes = 1, top = 10)
```

```{r}
# get percent PC contribution for each variable for PC 2
fviz_contrib(pca_mtcars, choice="var", axes = 2, top = 10)
```

